#+OPTIONS:    H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate 
#+TITLE:    MATHEMATICAL THINKING
#+AUTHOR:    teoten
#+EMAIL:     teoten@gmail.com
#+LANGUAGE:   en
#+STYLE:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+BABEL: :exports both

* REPOSITORY CONTENT
   - [ ] [[/Pythostabilization][Pythostabilization]]
   - [ ] Compochar

* DESCRIPTION

Visualisations are an important part of data processing which functions
can be to bring direct and clear impressions about certain insights 
contained within the unsorted or unstructured data, to give a wider 
overview of the information, particularly when the data is big (too many
entries or too many variables), or to represent the results of processing
the data, such as statistical analysis. Unfortunately, when a scientific 
paper is accepted in a per-review journal, the available space is too
small for the amount of data that a researcher can generate. More and
more journals are promoting and encouraging authors to add visualisations
as a complement to the limited capacity of a single scientific paper. The
idea of creating this repository is to have a space where I can show all
the data that is generated through my research. 

My PhD. in environmental geo-sciences took me to produce several data sets
with fair amounts of entries, but large amounts of variables. Due to the
multidisciplinarity of the topic, I have to work with chemical, ecological,
biological, environmental and geological variables. The results generated
by such research are always useful and interesting, however a visualisation
can make the difference between having impact or not. Here I try to
represent the data generated by my research increasing its visual value
and simplifying the language in a way that any person with no knowledge
on the topic should be able to understand.

On the other hand, the software intended to created data visualisations
is growing in a way that it starts becoming difficult to choose one tool
among so many. Different companies hiring data analysts demand skills with
different programs (SAP, Matlab, Power BI, tableau, etc.) and it is just
impossible to master them all. With this repository I will also try to 
show the advantages of using programming languages such as =R= and 
=python= for data visualisation, its simplicity and its scopes. Thus, the
increasing amount of data available on the web it's also used with the
same purposes of showing inputs contained within data sets.

Due to the limitations and capacity of GitHub, the raw data is not stored
here. However, if your interest for some specific data set grows while
browsing this site, feel free to contact me and I can share it.
